spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-dev
server:
  port: 3355



---
spring:
  profiles: test
  application: microservicecloud-config-clent-test
server:
  port: 9955
  
